const sendProducts = (req, res) => {
  res.json({
    data: [
      {
        key: 1,
        name: "나이트로 바닐라 크림",
        engname: "Nitro Vanilla Cream",
        imageURL: "/images/seulhaewon/coffee3.jpg",
        category: "콜드 브루 커피",
        categoryId: 1,
        alt: "coffee",
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 2,
        name: "나이트로 콜드 브루",
        engname: "nitro cold brew",
        imageURL: "/images/seulhaewon/coffee4.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 3,
        name: "돌체 콜드 브루",
        engname: "dolche cold brew",
        imageURL: "/images/seulhaewon/coffee5.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 4,
        name: "바닐라 크림 콜드 브루",
        engname: "banila cream cold brew",
        imageURL: "/images/seulhaewon/coffee6.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 5,
        name: "벨벳 다크 모카 나이트로",
        engname: "velvet dark mocha nitro",
        imageURL: "/images/seulhaewon/coffee7.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 6,
        name: "시그니처 더 블랙 콜드 브루",
        engname: "signature the black cold brew",
        imageURL: "/images/seulhaewon/coffee8.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 7,
        name: "제주 비자림 콜드 브루",
        engname: "jeju coffee",
        imageURL: "/images/seulhaewon/coffee9.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 8,
        name: "콜드 브루",
        engname: "cold brew",
        imageURL: "/images/seulhaewon/coffee10.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 9,
        name: "콜드 브루 몰트",
        engname: "cold brew molt",
        imageURL: "/images/seulhaewon/coffee11.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 10,
        name: "콜드 브루 오트 라떼",
        engname: "cold brew ort lattee",
        imageURL: "/images/seulhaewon/coffee12.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 11,
        name: "콜드 브루 플로트",
        engname: "cold brew float",
        imageURL: "/images/seulhaewon/coffee1.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 12,
        name: "프렌치 애플 타르트 나이트로",
        engname: "french apple nitro",
        imageURL: "/images/seulhaewon/coffee2.jpg",
        alt: "coffee",
        category: "콜드 브루 커피",
        categoryId: 1,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 13,
        name: "아이스 커피",
        engname: "ice coffee",
        imageURL: "/images/seulhaewon/coffee1.jpg",
        alt: "coffee",
        category: "브루드 커피",
        categoryId: 2,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
      {
        key: 14,
        name: "오늘의 커피",
        engname: "today's coffee",
        imageURL: "/images/seulhaewon/coffee2.jpg",
        alt: "coffee",
        category: "브루드 커피",
        categoryId: 2,
        Link: "/detail-haewon",
        heart: "FH",
        heartColor: "#CFCFCF",
      },
    ],
  });
};

module.exports = { sendProducts };
