const http = require('http')
const express = require('express')
const { sendCategorys } = require('./sendCategorys')
const { sendProducts } = require('./sendProducts')
const { sendItem1 } = require('./sendItem1')
const { sendItem2 } = require('./sendItem2')
const { sendItem3 } = require('./sendItem3')
const { sendItem4 } = require('./sendItem4')
const { sendItem5 } = require('./sendItem5')
const { sendItem6 } = require('./sendItem6')
const { sendItem7 } = require('./sendItem7')
const { sendItem8 } = require('./sendItem8')
const { sendItem9 } = require('./sendItem9')
const { sendItem10 } = require('./sendItem10')
const { sendItem11 } = require('./sendItem11')
const { sendItem12 } = require('./sendItem12')
const { sendItem13 } = require('./sendItem13')
const { sendItem14 } = require('./sendItem14')

const app = express()
app.use(express.json())

app.get('/', (req, res) => {
  res.json({ message: 'hello world!' })
})
app.get('/products', sendProducts)
app.get('/products/categories', sendCategorys)

app.get('/products/1', sendItem1)
app.get('/products/2', sendItem2)
app.get('/products/3', sendItem3)
app.get('/products/4', sendItem4)
app.get('/products/5', sendItem5)
app.get('/products/6', sendItem6)
app.get('/products/7', sendItem7)
app.get('/products/8', sendItem8)
app.get('/products/9', sendItem9)
app.get('/products/10', sendItem10)
app.get('/products/11', sendItem11)
app.get('/products/12', sendItem12)
app.get('/products/13', sendItem13)
app.get('/products/14', sendItem14)

const server = http.createServer(app)

server.listen(8000, () => {
  console.log('server is listening on PORT 8000')
})